// Harvests component props from the real widget constructors in astryx_widgets
// (syntactic analyzer parse — no type resolution) and writes them to
// lib/src/registry_props.g.dart. The registry then uses these harvested props
// for widget components, so its API surface can never silently drift from the
// code. Function-based entries (showAstryx*) keep their curated props.
//
// Run from packages/astryx_core:  dart run tool/gen_registry.dart
// ignore_for_file: deprecated_member_use
import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';

const _widgetSupers = {'StatelessWidget', 'StatefulWidget'};

void main() {
  final srcDir = Directory('../astryx_widgets/lib/src');
  if (!srcDir.existsSync()) {
    stderr.writeln(
      'Cannot find ${srcDir.path}. Run from packages/astryx_core.',
    );
    exit(1);
  }

  final harvested = <String, List<_Prop>>{};
  for (final entity in srcDir.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    if (entity.path.endsWith('.g.dart') ||
        entity.path.endsWith('.manifest.dart'))
      continue;
    final unit = parseString(
      content: entity.readAsStringSync(),
      throwIfDiagnostics: false,
    ).unit;
    for (final decl in unit.declarations) {
      if (decl is! ClassDeclaration) continue;
      final name = decl.name.lexeme;
      if (!name.startsWith('Astryx') || name.startsWith('_')) continue;
      final superName = decl.extendsClause?.superclass.name.lexeme;
      if (!_widgetSupers.contains(superName)) continue;
      final props = _propsOf(decl);
      if (props.isNotEmpty) harvested[name] = props;
    }
  }

  final out = File('lib/src/registry_props.g.dart');
  out.writeAsStringSync(_emit(harvested));
  stdout.writeln(
    'Harvested ${harvested.length} widget components → ${out.path}',
  );
}

List<_Prop> _propsOf(ClassDeclaration cls) {
  // Field name → (type, doc) so `this.foo` params get their declared type + doc.
  final fieldType = <String, String>{};
  final fieldDoc = <String, String>{};
  for (final m in cls.members) {
    if (m is! FieldDeclaration || m.isStatic) continue;
    final type = m.fields.type?.toSource() ?? 'dynamic';
    final doc = _docOf(m.documentationComment);
    for (final v in m.fields.variables) {
      fieldType[v.name.lexeme] = type;
      fieldDoc[v.name.lexeme] = doc;
    }
  }

  // The primary (unnamed) constructor, else the first constructor.
  ConstructorDeclaration? ctor;
  for (final m in cls.members) {
    if (m is ConstructorDeclaration) {
      ctor ??= m;
      if (m.name == null) {
        ctor = m;
        break;
      }
    }
  }
  if (ctor == null) return const [];

  final props = <_Prop>[];
  for (final param in ctor.parameters.parameters) {
    final normal = param is DefaultFormalParameter
        ? param.parameter
        : param as NormalFormalParameter;
    final pname = normal.name?.lexeme;
    if (pname == null || pname == 'key') continue;
    final def = param is DefaultFormalParameter
        ? param.defaultValue?.toSource()
        : null;
    props.add(
      _Prop(
        name: pname,
        type: fieldType[pname] ?? _inlineType(normal),
        required: param.isRequired,
        defaultValue: def,
        doc: fieldDoc[pname] ?? '',
      ),
    );
  }
  return props;
}

String _inlineType(NormalFormalParameter p) {
  if (p is SimpleFormalParameter) return p.type?.toSource() ?? 'dynamic';
  return 'dynamic';
}

String _docOf(Comment? comment) {
  if (comment == null) return '';
  final text = comment.tokens
      .map((t) => t.lexeme.replaceFirst(RegExp(r'^///?\s?'), ''))
      .join(' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
  return text.length > 160 ? '${text.substring(0, 157)}…' : text;
}

class _Prop {
  _Prop({
    required this.name,
    required this.type,
    required this.required,
    this.defaultValue,
    required this.doc,
  });
  final String name;
  final String type;
  final bool required;
  final String? defaultValue;
  final String doc;
}

String _dartStr(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$').replaceAll('\n', ' ')}'";

String _emit(Map<String, List<_Prop>> harvested) {
  final names = harvested.keys.toList()..sort();
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_registry.dart — do not edit by hand.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars, require_trailing_commas')
    ..writeln(
      '// Props harvested from the real widget constructors in astryx_widgets,',
    )
    ..writeln('// so the registry API surface cannot drift from the code.')
    ..writeln("import 'model.dart';")
    ..writeln()
    ..writeln('const Map<String, List<AstryxProp>> harvestedProps = {');
  for (final name in names) {
    b.writeln("  '$name': [");
    for (final p in harvested[name]!) {
      final parts = <String>[_dartStr(p.name), _dartStr(p.type)];
      if (p.required) parts.add('required: true');
      if (p.defaultValue != null)
        parts.add('defaultValue: ${_dartStr(p.defaultValue!)}');
      if (p.doc.isNotEmpty) parts.add('doc: ${_dartStr(p.doc)}');
      b.writeln('    AstryxProp(${parts.join(', ')}),');
    }
    b.writeln('  ],');
  }
  b.writeln('};');
  return b.toString();
}
